# Generated by Django 5.2.7 on 2026-07-26 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('lead_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('MATERIAL', 'Material Based'), ('LABOR', 'Labor Only')], default='LABOR', max_length=10)),
                ('items', models.JSONField(blank=True, default=list)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thank_you_note', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.branchmanagement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='lead_management.customer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.sitemanagement')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotation.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLowSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_data', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_side_items', to='quotation.quotationversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationHighSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_side_items', to='quotation.quotationversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='quotation.quotationversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.servicemaster')),
            ],
        ),
        migrations.CreateModel(
            name='TermsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Term title/heading', max_length=255)),
                ('content', models.TextField(help_text='Full term description/content')),
                ('sequence', models.IntegerField(default=1, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Automatically included in new quotations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms & Conditions Master',
                'verbose_name_plural': 'Terms & Conditions Masters',
                'ordering': ['sequence', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuotationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sequence', models.IntegerField(default=1)),
                ('is_customized', models.BooleanField(default=False, help_text='True if this term was modified from the master')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='quotation.quotation')),
                ('master_term', models.ForeignKey(blank=True, help_text='Reference to master term if not customized', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.termsmaster')),
            ],
            options={
                'verbose_name': 'Quotation Terms & Conditions',
                'verbose_name_plural': 'Quotation Terms & Conditions',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_no'), name='unique_quotation_version'),
        ),
        migrations.AlterUniqueTogether(
            name='quotationterms',
            unique_together={('quotation', 'sequence')},
        ),
    ]
