# Generated by Django 5.2.3 on 2026-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationversion',
            name='insurance_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='loading_unloading_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='miscellaneous_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='packing_forwarding_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='transportation_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
