# Generated by Django 5.2.3 on 2026-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotationversion_insurance_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationversion',
            name='insurance_charges_type',
            field=models.CharField(blank=True, default='custom', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='loading_unloading_charges_type',
            field=models.CharField(blank=True, default='custom', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='miscellaneous_charges_type',
            field=models.CharField(blank=True, default='custom', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='packing_forwarding_charges_type',
            field=models.CharField(blank=True, default='custom', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='transportation_charges_type',
            field=models.CharField(blank=True, default='custom', max_length=50, null=True),
        ),
    ]
