# Generated by Django 5.2.3 on 2026-08-29 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotationversion_insurance_charges_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_as_sales_person', to=settings.AUTH_USER_MODEL, verbose_name='Sales Person'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sales Person Name'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_person_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sales Person Mobile'),
        ),
    ]
