# Generated by Django 5.2.3 on 2026-09-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Contract ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Name')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('amc_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('non_comprehensive', 'Non-Comprehensive'), ('warranty', '1 Year Warranty (4 Quarterly Free Services)')], default='comprehensive', max_length=50, verbose_name='AMC Type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Annual Value (₹)')),
                ('payment_frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly')], default='quarterly', max_length=50, verbose_name='Payment Frequency')),
                ('scope_of_support', models.TextField(blank=True, null=True, verbose_name='Scope of Support')),
                ('per_visit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Per Visit Amount (₹)')),
                ('default_customer_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Customer Contact')),
                ('default_customer_address', models.TextField(blank=True, null=True, verbose_name='Default Customer Address')),
                ('default_gps_location', models.URLField(blank=True, null=True, verbose_name='Default GPS Location')),
                ('default_work_description', models.TextField(blank=True, null=True, verbose_name='Default Work Description')),
                ('renewal_status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_RENEWED', 'Not Renewed')], default='PENDING', max_length=20, verbose_name='Renewal Status')),
                ('renewal_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Renewal Requested At')),
                ('expiry_reminder_2days_sent', models.BooleanField(default=False, verbose_name='2-Day Expiry Reminder Email Sent')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('scheduled', 'Scheduled'), ('renewed', 'Renewed')], default='active', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AMC Contract',
                'verbose_name_plural': 'AMC Contracts',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMCCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1, verbose_name='Cycle #')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Annual Value (₹)')),
                ('payment_frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly')], default='quarterly', max_length=50, verbose_name='Payment Frequency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('scheduled', 'Scheduled'), ('renewed', 'Renewed')], default='active', max_length=50, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Notes / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'AMC Cycle',
                'verbose_name_plural': 'AMC Cycles',
                'ordering': ['-cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='AMCRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Customer Requested Renewal'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected'), ('NOT_RENEWED', 'Customer Declined Renewal'), ('COMPLETED', 'Renewal Completed (New Cycle Created)')], default='PENDING', max_length=20, verbose_name='Renewal Status')),
                ('customer_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Customer Requested At')),
                ('customer_response', models.TextField(blank=True, null=True, verbose_name='Customer Response/Notes')),
                ('admin_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AMC Renewal Request',
                'verbose_name_plural': 'AMC Renewal Requests',
                'db_table': 'amc_renewals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMCServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Scheduled Service Date')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Reminder Email Sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Sent At')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by Admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'AMC Service Schedule',
                'verbose_name_plural': 'AMC Service Schedules',
                'db_table': 'amc_service_schedules',
                'ordering': ['service_date'],
            },
        ),
        migrations.CreateModel(
            name='AMCServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('crm_service_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Service Request Created At')),
                ('allocation_status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Allocation Status')),
                ('auto_allocation_done', models.BooleanField(default=False, verbose_name='Auto Allocated by System')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Visit Remarks')),
                ('allocation_cancelled_reason', models.TextField(blank=True, null=True, verbose_name='Cancellation Reason')),
                ('rescheduled_from', models.DateField(blank=True, null=True, verbose_name='Original Date (if rescheduled)')),
                ('reschedule_reason', models.TextField(blank=True, null=True, verbose_name='Reschedule Reason')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Reminder Email Sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AMC Service Visit',
                'verbose_name_plural': 'AMC Service Visits',
                'db_table': 'amc_service_visits',
                'ordering': ['-service_date'],
            },
        ),
    ]
