# Generated by Django 4.2.24 on 2026-08-10 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Contract ID')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('amc_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('non_comprehensive', 'Non-Comprehensive')], default='comprehensive', max_length=50, verbose_name='AMC Type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Annual Value (₹)')),
                ('payment_frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly')], default='quarterly', max_length=50, verbose_name='Payment Frequency')),
                ('scope_of_support', models.TextField(blank=True, null=True, verbose_name='Scope of Support')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewal_pending', 'Renewal Pending')], default='active', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='lead_management.customer', verbose_name='Customer')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Name')),
                ('support_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_amcs', to=settings.AUTH_USER_MODEL, verbose_name='Support Coordinator')),
            ],
            options={
                'verbose_name': 'AMC Contract',
                'verbose_name_plural': 'AMC Contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
