# Generated by Django 4.2.24 on 2026-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
