# Generated by Django 5.2.3 on 2026-09-11 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amc', '0001_initial'),
        ('lead_management', '0011_lead_management_customer_layout_and_more'),
        ('product_management', '0001_initial'),
        ('service_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_amcs', to='service_management.technician', verbose_name='Assigned Technician'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='lead_management.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='linked_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_amc_contracts', to='service_management.servicerequest', verbose_name='Linked Service Call'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='support_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_amcs', to=settings.AUTH_USER_MODEL, verbose_name='Support Coordinator'),
        ),
        migrations.AddField(
            model_name='amccycle',
            name='amc_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='amc.amccontract', verbose_name='AMC Contract'),
        ),
        migrations.AddField(
            model_name='amccycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_cycles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='amcrenewal',
            name='admin_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_renewals_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='amcrenewal',
            name='amc_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='amc.amccontract', verbose_name='AMC Contract'),
        ),
        migrations.AddField(
            model_name='amcrenewal',
            name='new_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_record', to='amc.amccycle', verbose_name='New Cycle Created'),
        ),
        migrations.AddField(
            model_name='amcserviceschedule',
            name='amc_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='amc.amccontract', verbose_name='AMC Contract'),
        ),
        migrations.AddField(
            model_name='amcserviceschedule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='amc_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='amc.amccontract', verbose_name='AMC Contract'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='crm_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_visit_records', to='service_management.servicerequest', verbose_name='Linked Service Request'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_visits', to='product_management.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='amc_service_visits', to='service_management.technician', verbose_name='Assigned Technicians'),
        ),
        migrations.AlterUniqueTogether(
            name='amcserviceschedule',
            unique_together={('amc_contract', 'service_date')},
        ),
    ]
