# Generated by Django 5.2.7 on 2026-07-26 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amc', '0001_initial'),
        ('api', '0001_initial'),
        ('lead_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amc_contracts', to='lead_management.customer'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='previous_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amccontract'),
        ),
        migrations.AddField(
            model_name='amcrenewal',
            name='new_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='amc.amccontract'),
        ),
        migrations.AddField(
            model_name='amcrenewal',
            name='previous_contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to='amc.amccontract'),
        ),
        migrations.AddField(
            model_name='servicemanagementrecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.branchmanagement'),
        ),
        migrations.AddField(
            model_name='servicemanagementrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicemanagementrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_management_records', to='lead_management.customer'),
        ),
        migrations.AddField(
            model_name='servicemanagementmaterial',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='amc.servicemanagementrecord'),
        ),
    ]
