# Generated by Django 4.2.24 on 2026-08-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amc', '0002_alter_amccontract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCRenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_number', models.PositiveIntegerField(default=1, verbose_name='Renewal Cycle #')),
                ('old_start_date', models.DateField(blank=True, null=True)),
                ('old_end_date', models.DateField(blank=True, null=True)),
                ('old_annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('new_annual_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_frequency', models.CharField(default='quarterly', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Renewal Notes / Remarks')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('amc_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='amc.amccontract', verbose_name='AMC Contract')),
                ('renewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AMC Renewal History',
                'verbose_name_plural': 'AMC Renewal Histories',
                'ordering': ['-renewal_number'],
            },
        ),
    ]
