# Generated by Django 5.2.7 on 2026-07-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMCSparePart',
        ),
    ]
