# Generated by Django 4.2.24 on 2026-08-10 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amc', '0003_amcrenewalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1, verbose_name='Cycle #')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('annual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Annual Value (₹)')),
                ('payment_frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('half_yearly', 'Half-Yearly')], default='quarterly', max_length=50, verbose_name='Payment Frequency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='active', max_length=50, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Notes / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'AMC Cycle',
                'verbose_name_plural': 'AMC Cycles',
                'ordering': ['-cycle_number'],
            },
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('scheduled', 'Scheduled'), ('renewed', 'Renewed')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='AMCRenewalHistory',
        ),
        migrations.AddField(
            model_name='amccycle',
            name='amc_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='amc.amccontract', verbose_name='AMC Contract'),
        ),
        migrations.AddField(
            model_name='amccycle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_cycles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
