# Generated by Django 4.2.24 on 2026-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_amccycle_alter_amccontract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccycle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('scheduled', 'Scheduled'), ('renewed', 'Renewed')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
