# Generated by Django 5.2.3 on 2026-08-19 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0006_alter_amccontract_options'),
        ('service_management', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_amcs', to='service_management.technician', verbose_name='Assigned Technician'),
        ),
    ]
