# Generated by Django 5.2.3 on 2026-08-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0007_amccontract_assigned_technician'),
        ('service_management', '0002_servicerequest_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='linked_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_amc_contracts', to='service_management.servicerequest', verbose_name='Linked Service Call'),
        ),
    ]
