# Generated by Django 5.2.7 on 2026-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0008_amccontract_linked_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='amc_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('non_comprehensive', 'Non-Comprehensive'), ('warranty', '1 Year Warranty (4 Quarterly Free Services)')], default='comprehensive', max_length=50, verbose_name='AMC Type'),
        ),
    ]
