# Generated by Django 5.2.3 on 2026-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0009_alter_amccontract_amc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='default_customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Default Customer Address'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_customer_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Customer Contact'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_gps_location',
            field=models.URLField(blank=True, null=True, verbose_name='Default GPS Location'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='default_work_description',
            field=models.TextField(blank=True, null=True, verbose_name='Default Work Description'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='per_visit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Per Visit Amount (₹)'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Renewal Requested At'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_RENEWED', 'Not Renewed')], default='PENDING', max_length=20, verbose_name='Renewal Status'),
        ),
    ]
