# Generated by Django 5.2.3 on 2026-08-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0010_amccontract_default_customer_address_and_more'),
        ('product_management', '0001_initial'),
        ('service_management', '0004_servicerequest_is_allocated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Customer Requested Renewal'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected'), ('NOT_RENEWED', 'Customer Declined Renewal'), ('COMPLETED', 'Renewal Completed (New Cycle Created)')], default='PENDING', max_length=20, verbose_name='Renewal Status')),
                ('customer_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Customer Requested At')),
                ('customer_response', models.TextField(blank=True, null=True, verbose_name='Customer Response/Notes')),
                ('admin_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_renewals_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('amc_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='amc.amccontract', verbose_name='AMC Contract')),
                ('new_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_record', to='amc.amccycle', verbose_name='New Cycle Created')),
            ],
            options={
                'verbose_name': 'AMC Renewal Request',
                'verbose_name_plural': 'AMC Renewal Requests',
                'db_table': 'amc_renewals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMCServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('crm_service_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Service Request Created At')),
                ('allocation_status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Allocation Status')),
                ('auto_allocation_done', models.BooleanField(default=False, verbose_name='Auto Allocated by System')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Visit Remarks')),
                ('allocation_cancelled_reason', models.TextField(blank=True, null=True, verbose_name='Cancellation Reason')),
                ('rescheduled_from', models.DateField(blank=True, null=True, verbose_name='Original Date (if rescheduled)')),
                ('reschedule_reason', models.TextField(blank=True, null=True, verbose_name='Reschedule Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amc_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='amc.amccontract', verbose_name='AMC Contract')),
                ('crm_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_visit_records', to='service_management.servicerequest', verbose_name='Linked Service Request')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_visits', to='product_management.product', verbose_name='Product')),
                ('technicians', models.ManyToManyField(blank=True, related_name='amc_service_visits', to='service_management.technician', verbose_name='Assigned Technicians')),
            ],
            options={
                'verbose_name': 'AMC Service Visit',
                'verbose_name_plural': 'AMC Service Visits',
                'db_table': 'amc_service_visits',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='AMCServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Scheduled Service Date')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Reminder Email Sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Sent At')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by Admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('amc_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='amc.amccontract', verbose_name='AMC Contract')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
            ],
            options={
                'verbose_name': 'AMC Service Schedule',
                'verbose_name_plural': 'AMC Service Schedules',
                'db_table': 'amc_service_schedules',
                'ordering': ['service_date'],
                'unique_together': {('amc_contract', 'service_date')},
            },
        ),
    ]
