# Generated by Django 5.2.7 on 2026-09-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0011_amcrenewal_amcservicevisit_amcserviceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='expiry_reminder_2days_sent',
            field=models.BooleanField(default=False, verbose_name='2-Day Expiry Reminder Email Sent'),
        ),
    ]
