# Generated by Django 5.2.7 on 2026-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0012_amccontract_expiry_reminder_2days_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcservicevisit',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder Email Sent'),
        ),
        migrations.AddField(
            model_name='amcservicevisit',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reminder Sent At'),
        ),
    ]
