# Generated by Django 5.2.3 on 2026-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0014_amccontract_contract_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='amccontract',
                    name='contract_id',
                    field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Contract ID'),
                ),
            ],
            database_operations=[]
        )
    ]

