# Generated by Django 5.2.7 on 2026-07-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('inventory', '0001_initial'),
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=255)),
                ('declaration', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_gstin', models.CharField(max_length=20)),
                ('buyer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_to_address', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('declaration', models.TextField(blank=True, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note_date', models.DateField(blank=True, null=True, verbose_name='Delivery Note Date')),
                ('delivery_chalan_date', models.DateField(blank=True, null=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('other_references', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_dated', models.DateField(blank=True, null=True, verbose_name='Buyer Order Date')),
                ('dispatch_doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatched_through', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(default=dict)),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST'), ('NO_GST', 'No GST')], default='CGST_SGST', max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branchmanagement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='lead_management.customer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.sitemanagement')),
                ('terms_conditions', models.ManyToManyField(blank=True, related_name='invoices', to='inventory.termsconditions')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHighSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_side_items', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLowSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_data', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_side_items', to='invoice.invoice')),
            ],
        ),
    ]
