# Generated by Django 5.2.3 on 2026-07-29 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stack_parking', 'Stack Parking'), ('puzzle_parking', 'Puzzle Parking'), ('tower_parking', 'Tower Parking'), ('pit_parking', 'Pit Parking'), ('cantilever', 'Cantilever Parking')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='e.g., 2DP 101', max_length=200, unique=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('levels', models.PositiveIntegerField(help_text='Number of levels', validators=[django.core.validators.MinValueValidator(1)])),
                ('operation_type', models.CharField(choices=[('hydraulic', 'Hydraulic'), ('mechanical', 'Mechanical'), ('hybrid', 'Hybrid')], default='hydraulic', max_length=50)),
                ('automation_type', models.CharField(choices=[('fully_automatic', 'Fully Automatic'), ('semi_automatic', 'Semi Automatic'), ('manual', 'Manual')], default='semi_automatic', max_length=50)),
                ('pit_required', models.BooleanField(default=False)),
                ('load_capacity', models.DecimalField(decimal_places=2, help_text='Load capacity in KG', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_height', models.DecimalField(decimal_places=2, help_text='Minimum height required (ft)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_width', models.DecimalField(decimal_places=2, help_text='Minimum width required (ft)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_length', models.DecimalField(decimal_places=2, help_text='Minimum length required (ft)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('car_capacity', models.PositiveIntegerField(help_text='Total car capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('features', models.JSONField(blank=True, default=list, help_text='List of product features')),
                ('advantages', models.JSONField(blank=True, default=list, help_text='List of product advantages')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Additional specifications')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price (optional)', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Uploaded product image', null=True, upload_to='parking_products/')),
                ('image_url', models.TextField(blank=True, help_text='External image URL or Base64 data (optional)', null=True)),
                ('brochure_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='parking_products.productcategory')),
            ],
            options={
                'verbose_name': 'Parking Product',
                'verbose_name_plural': 'Parking Products',
                'db_table': 'parking_products',
                'ordering': ['-is_featured', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=200)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('levels', models.PositiveIntegerField()),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for this configuration', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='parking_products.parkingproduct')),
            ],
            options={
                'verbose_name': 'Product Configuration',
                'verbose_name_plural': 'Product Configurations',
                'db_table': 'product_configurations',
            },
        ),
        migrations.AddIndex(
            model_name='parkingproduct',
            index=models.Index(fields=['category', 'is_active'], name='parking_pro_categor_6fdc00_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingproduct',
            index=models.Index(fields=['product_name'], name='parking_pro_product_02d683_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productconfiguration',
            unique_together={('product', 'variant_name')},
        ),
    ]
