# Generated by Django 5.2.3 on 2026-08-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in feet', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in feet', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in feet', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in INR', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='parking_products.productcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='parking_products.parkingproduct')),
            ],
            options={
                'verbose_name': 'Product Requirement',
                'verbose_name_plural': 'Product Requirements',
                'db_table': 'product_requirements',
                'ordering': ['-created_at'],
                'unique_together': {('category', 'product')},
            },
        ),
    ]
