# Generated by Django 5.2.3 on 2026-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_products', '0002_productrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='car_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Car Length in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='car_width_mirror_open',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Car Width (Mirror Open) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='ground_car_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ground Car Height in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='height_available',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height Available (H) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='pit_car_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pit Car Height (P2) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='pit_depth_available',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pit Depth Available (P1) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='platform_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform Length in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='platform_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform Width (W) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='platform_width_middle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform Width (MIDDLE P) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='platform_width_top',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform Width (TOP P) in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='total_available_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Available Length in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='total_width_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Width Required in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='upper_car_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper Car Height (G+1) in mm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in feet or mm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in feet or mm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in feet or mm', max_digits=10, null=True),
        ),
    ]
