# Generated by Django 5.2.3 on 2026-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_products', '0003_delete_productrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('stack_parking', 'Stack Parking'), ('puzzle_parking', 'Puzzle Parking'), ('tower_parking', 'Tower Parking'), ('pit_parking', 'Pit Parking'), ('pit_stack_parking', 'Pit Stack Parking'), ('pit_puzzle_parking', 'Pit Puzzle Parking'), ('cantilever', 'Cantilever Parking')], max_length=100, unique=True),
        ),
    ]
