# Generated by Django 5.2.3 on 2026-09-07 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_products', '0004_alter_productcategory_name'),
    ]

    operations = [
    ]
