# Generated by Django 5.2.3 on 2026-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product / Equipment'),
        ),
    ]
