# Generated by Django 5.2.7 on 2026-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0002_servicerequest_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('warranty', 'Warranty Service'), ('amc', 'AMC Service'), ('normal', 'Normal Service')], default='normal', max_length=50, verbose_name='Service Type'),
        ),
    ]
