# Generated by Django 5.2.3 on 2026-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0003_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_allocated',
            field=models.BooleanField(default=False, verbose_name='Is Allocated'),
        ),
    ]
