# Generated by Django 5.2.3 on 2026-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0004_servicerequest_is_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='after_service_photo',
            field=models.TextField(blank=True, null=True, verbose_name='After Service Photo'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='before_service_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Before Service Photo'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_approval',
            field=models.BooleanField(default=False, verbose_name='Customer Approved'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Signature'),
        ),
    ]
