# Generated by Django 5.2.7 on 2026-09-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0005_servicerequest_after_service_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='reminder_2days_sent',
            field=models.BooleanField(default=False, verbose_name='2-Day Reminder Email Sent'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reminder_2days_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2-Day Reminder Sent At'),
        ),
    ]
