# Generated by Django 5.2.7 on 2026-07-09 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_type', models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST'), ('EXEMPT', 'Exempt'), ('NIL', 'Nil Rated')], default='GST', max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('DAMAGED', 'Damaged'), ('RESERVED', 'Reserved')], default='IN_STOCK', max_length=20)),
                ('warehouse', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('is_serialized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='product_management.product')),
            ],
        ),
    ]
