# Generated by Django 5.2.3 on 2026-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
