# Generated by Django 5.2.7 on 2026-07-09 12:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(blank=True, default=dict)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_in_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_out_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('office_address', models.TextField()),
                ('gst_details', models.CharField(max_length=15)),
                ('office_poc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('office_poc_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('supplier_category', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_details', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('store_poc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_poc_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=50, unique=True)),
                ('issue_type', models.CharField(choices=[('site', 'Site'), ('technician', 'Technician')], max_length=20)),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branchmanagement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.sitemanagement')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('dispatch_date', models.DateField()),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_proof', models.FileField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='inventory.materialissue')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialissue')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.deliverychallan')),
                ('material_issue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.materialissueitem')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('return_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.materialissue')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_issue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.materialissueitem')),
                ('material_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialreturn')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField(blank=True, null=True)),
                ('book_no', models.CharField(max_length=10)),
                ('purchase_order_no', models.CharField(blank=True, max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('quotation_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_destination', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=20)),
                ('transport_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)])),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.branchmanagement')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.sitemanagement')),
                ('terms_conditions', models.ManyToManyField(blank=True, related_name='purchase_orders', to='inventory.termsconditions')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor')),
            ],
            options={
                'unique_together': {('purchase_order_no', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('grn_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='inventory.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(blank=True, default=dict)),
                ('serial_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_section', models.BooleanField(default=False)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GRNProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(blank=True, default=dict)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.grn')),
                ('purchase_order_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.purchaseorderproduct')),
            ],
        ),
        migrations.AddField(
            model_name='termsconditions',
            name='terms_condition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='inventory.termsconditiontype'),
        ),
    ]
