# Generated by Django 5.2.7 on 2026-07-09 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('poc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('poc_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('land_line_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('both_address_is_same', models.BooleanField(default=False)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('site_city', models.CharField(blank=True, max_length=100, null=True)),
                ('site_state', models.CharField(blank=True, max_length=100, null=True)),
                ('site_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='lead_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_details', models.TextField(blank=True)),
                ('lead_type', models.CharField(blank=True, max_length=200, null=True)),
                ('lead_source', models.CharField(max_length=200)),
                ('is_service_lead', models.CharField(blank=True, choices=[('sales', 'Sales'), ('service', 'Service'), ('both', 'Both')], max_length=20, null=True)),
                ('service_type', models.JSONField(blank=True, null=True)),
                ('lead_source_input', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_adderess', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_qualified', models.BooleanField(default=False)),
                ('qualifying_answers', models.JSONField(blank=True, default=dict, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignment', to=settings.AUTH_USER_MODEL)),
                ('creatd_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='lead_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='lead_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='lead_management.lead_management')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='lead_management.lead_management')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_data', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lead_management.leadfollowup')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUpFAQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lead_management.leadfaq')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_answers', to='lead_management.leadfollowup')),
            ],
            options={
                'unique_together': {('followup', 'faq')},
            },
        ),
    ]
