# Generated by Django 4.2.24 on 2026-07-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfollowupproduct',
            name='followup',
        ),
        migrations.DeleteModel(
            name='lead_product',
        ),
        migrations.DeleteModel(
            name='LeadFollowUpProduct',
        ),
    ]
