# Generated by Django 5.2.3 on 2026-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='last_followup_date',
        ),
        migrations.AddField(
            model_name='lead_management',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_question',
            field=models.TextField(blank=True, help_text='Follow-up question or inquiry details', null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='site_name',
            field=models.CharField(blank=True, help_text='Site name or project site location', max_length=255, null=True),
        ),
    ]
