# Generated by Django 5.2.3 on 2026-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0002_remove_lead_management_last_followup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='last_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
