# Generated by Django 5.2.3 on 2026-07-15 10:20

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_update_followup_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadfollowup',
            options={'ordering': ['-followup_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
