# Generated by Django 5.2.3 on 2026-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_lead_management_last_followup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
