# Generated by Django 5.2.3 on 2026-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_lead_management_is_received_lead_management_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close_win', 'Close Win'), ('close_loss', 'Close Loss'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=200),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close_win', 'Close Win'), ('close_loss', 'Close Loss'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=200),
        ),
    ]
