# Generated by Django 5.2.3 on 2026-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_alter_leadfollowup_options_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='requirement_info',
            field=models.JSONField(blank=True, help_text='Site requirements: length, width, height, parking type, automation', null=True),
        ),
    ]
