# Generated by Django 5.2.3 on 2026-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_alter_lead_management_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='site_photo',
            field=models.ImageField(blank=True, help_text='Site photo taken during follow-up', null=True, upload_to='followup_site_photos/'),
        ),
    ]
