# Generated by Django 5.2.3 on 2026-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_leadfollowup_requirement_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='qualifying_info',
            field=models.JSONField(blank=True, help_text='Qualifying questions: site location, cars required, car type, budget, etc.', null=True),
        ),
    ]
