# Generated by Django 5.2.3 on 2026-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0006_leadfollowup_site_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='cad_design_required',
            field=models.BooleanField(default=False, help_text='CAD Design required for lead'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='cad_file',
            field=models.FileField(blank=True, null=True, upload_to='lead_cad_drawings/'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='cad_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='cad_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_required', max_length=50),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='layout_design_required',
            field=models.BooleanField(default=False, help_text='Layout Design required for lead'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='layout_file',
            field=models.FileField(blank=True, null=True, upload_to='lead_layouts/'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='layout_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='layout_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_required', max_length=50),
        ),
    ]
