# Generated by Django 5.2.3 on 2026-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0007_lead_management_cad_design_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='cad_files',
            field=models.JSONField(blank=True, default=list, help_text='Multiple uploaded CAD files list', null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='layout_files',
            field=models.JSONField(blank=True, default=list, help_text='Multiple uploaded layout files list', null=True),
        ),
    ]
