# Generated by Django 5.2.7 on 2026-07-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_customer_is_lead_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_lead_only',
            field=models.BooleanField(default=False),
        ),
    ]
