# Generated by Django 5.2.3 on 2026-08-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_lead_management_cad_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='cad_design_required',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='cad_file',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='cad_files',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='cad_notes',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='cad_status',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='layout_design_required',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='layout_file',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='layout_files',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='layout_notes',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='layout_status',
        ),
    ]
