# Generated by Django 5.2.3 on 2026-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0009_remove_lead_management_cad_design_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='cad_file',
            field=models.FileField(blank=True, null=True, upload_to='lead_cad_files/'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='cad_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
