# Generated by Django 5.2.3 on 2026-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0009_alter_customer_is_lead_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='client_commitment',
            field=models.TextField(blank=True, help_text='What the client committed to do', null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='contacted_person',
            field=models.CharField(blank=True, help_text='Person contacted during follow-up', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('scheduled', 'Scheduled')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('whatsapp', 'WhatsApp'), ('site_visit', 'Site Visit')], default='call', max_length=20),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='our_commitment',
            field=models.TextField(blank=True, help_text='What we committed to do', null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='previous_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20),
        ),
    ]
