# Generated by Django 5.2.3 on 2026-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0010_lead_management_cad_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='customer_layout',
            field=models.FileField(blank=True, help_text='Layout drawing/file provided by customer', null=True, upload_to='customer_layouts/'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='customer_layout_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='customer_layout_url',
            field=models.TextField(blank=True, help_text='Data URL or Base64 or external link of customer layout', null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='site_location',
            field=models.CharField(blank=True, help_text='Site Location / Project Address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='site_requirement',
            field=models.TextField(blank=True, help_text='Site Requirements & Design Specifications', null=True),
        ),
    ]
