# Generated by Django 5.2.3 on 2026-07-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0010_leadfollowup_client_commitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfollowup',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='client_response',
            field=models.CharField(choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('no_response', 'No Response'), ('call_back_later', 'Call Back Later')], default='neutral', help_text="Client's response sentiment", max_length=20),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='conducted_by',
            field=models.CharField(blank=True, help_text='Team member who conducted the follow-up', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_summary',
            field=models.TextField(blank=True, help_text='Key discussion points and summary', null=True),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('video_call', 'Video Call'), ('in_person', 'In-Person'), ('demo', 'Demo'), ('site_visit', 'Site Visit')], default='call', help_text='Follow-up mode: Call, WhatsApp, Email, Video Call, In-Person, Demo, Site Visit', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='qualifying_info',
            field=models.JSONField(blank=True, help_text='Qualifying questions: decision maker, budget, timeline, site details, etc.', null=True),
        ),
    ]
